# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class Response(BaseModel):
    grammatical_errors_present: typing.Optional[bool] = Field(default=None, description='True if there are any grammatical errors in the transcript')
    corrected_transcript: typing.Optional[str] = Field(default=None, description='The corrected transcript of the user\'s speech')
    explanation_for_student: typing.Optional[str] = Field(default=None, description='The explanation for the student in a conversational tone')

class Response2(BaseModel):
    acknowledgement: typing.Optional[str] = Field(default=None, description='Say a small acknowledgement for the users input')
    is_answer_satisfactory: typing.Optional[bool] = Field(default=None, description='Say whether the answer is correct or not')
    evidence_for_satisfaction: typing.Optional[str] = Field(default=None, description='Provide evidence that user answer is satisfactory')
    probe_question: typing.Optional[str] = Field(default=None, description='Provide a question for the user if answer is not satisfactory to probe them further. Only make this field non-empty if the answer is not satisfactory.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
