# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (1)
# #########################################################################

class Response(BaseModel):
    grammatical_errors_present: typing.Optional[bool] = Field(default=None, description='True if there are any grammatical errors in the transcript')
    corrected_transcript: typing.Optional[str] = Field(default=None, description='The corrected transcript of the user\'s speech')
    explanation_for_student: typing.Optional[str] = Field(default=None, description='The explanation for the student in a conversational tone')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
