# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def EvaluationLayer1(self, chat_history: str,current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.EvaluationLayerModel1:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.EvaluationLayer1(chat_history=chat_history,current_question=current_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="EvaluationLayer1", args={
                "chat_history": chat_history,"current_question": current_question,
            })
            return typing.cast(types.EvaluationLayerModel1, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def EvaluationLayer2(self, chat_history: str,current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.EvaluationLayerModel2:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.EvaluationLayer2(chat_history=chat_history,current_question=current_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="EvaluationLayer2", args={
                "chat_history": chat_history,"current_question": current_question,
            })
            return typing.cast(types.EvaluationLayerModel2, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def EvaluationLayer3(self, chat_history: str,diagnostic_goal: str,expected_fields: typing.List[str],current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.EvaluationLayerModel3:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.EvaluationLayer3(chat_history=chat_history,diagnostic_goal=diagnostic_goal,expected_fields=expected_fields,current_question=current_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="EvaluationLayer3", args={
                "chat_history": chat_history,"diagnostic_goal": diagnostic_goal,"expected_fields": expected_fields,"current_question": current_question,
            })
            return typing.cast(types.EvaluationLayerModel3, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GetResponse(self, chat_history: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Response:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GetResponse(chat_history=chat_history,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GetResponse", args={
                "chat_history": chat_history,
            })
            return typing.cast(types.Response, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GetResponse2(self, chat_history: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Response2:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GetResponse2(chat_history=chat_history,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GetResponse2", args={
                "chat_history": chat_history,
            })
            return typing.cast(types.Response2, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GetResponse3(self, chat_history: str,diagnostic_goal: str,expected_fields: typing.List[str],current_question: int,
        baml_options: BamlCallOptions = {},
    ) -> types.Response3:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GetResponse3(chat_history=chat_history,diagnostic_goal=diagnostic_goal,expected_fields=expected_fields,current_question=current_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GetResponse3", args={
                "chat_history": chat_history,"diagnostic_goal": diagnostic_goal,"expected_fields": expected_fields,"current_question": current_question,
            })
            return typing.cast(types.Response3, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GetResponse4(self, chat_history: str,current_question: int,
        baml_options: BamlCallOptions = {},
    ) -> types.Response4:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GetResponse4(chat_history=chat_history,current_question=current_question,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GetResponse4", args={
                "chat_history": chat_history,"current_question": current_question,
            })
            return typing.cast(types.Response4, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluationLayer1(self, chat_history: str,current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.EvaluationLayerModel1, types.EvaluationLayerModel1]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="EvaluationLayer1", args={
            "chat_history": chat_history,"current_question": current_question,
        })
        return baml_py.BamlSyncStream[stream_types.EvaluationLayerModel1, types.EvaluationLayerModel1](
          __result__,
          lambda x: typing.cast(stream_types.EvaluationLayerModel1, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.EvaluationLayerModel1, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def EvaluationLayer2(self, chat_history: str,current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.EvaluationLayerModel2, types.EvaluationLayerModel2]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="EvaluationLayer2", args={
            "chat_history": chat_history,"current_question": current_question,
        })
        return baml_py.BamlSyncStream[stream_types.EvaluationLayerModel2, types.EvaluationLayerModel2](
          __result__,
          lambda x: typing.cast(stream_types.EvaluationLayerModel2, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.EvaluationLayerModel2, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def EvaluationLayer3(self, chat_history: str,diagnostic_goal: str,expected_fields: typing.List[str],current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.EvaluationLayerModel3, types.EvaluationLayerModel3]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="EvaluationLayer3", args={
            "chat_history": chat_history,"diagnostic_goal": diagnostic_goal,"expected_fields": expected_fields,"current_question": current_question,
        })
        return baml_py.BamlSyncStream[stream_types.EvaluationLayerModel3, types.EvaluationLayerModel3](
          __result__,
          lambda x: typing.cast(stream_types.EvaluationLayerModel3, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.EvaluationLayerModel3, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GetResponse(self, chat_history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Response, types.Response]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GetResponse", args={
            "chat_history": chat_history,
        })
        return baml_py.BamlSyncStream[stream_types.Response, types.Response](
          __result__,
          lambda x: typing.cast(stream_types.Response, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Response, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GetResponse2(self, chat_history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Response2, types.Response2]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GetResponse2", args={
            "chat_history": chat_history,
        })
        return baml_py.BamlSyncStream[stream_types.Response2, types.Response2](
          __result__,
          lambda x: typing.cast(stream_types.Response2, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Response2, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GetResponse3(self, chat_history: str,diagnostic_goal: str,expected_fields: typing.List[str],current_question: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Response3, types.Response3]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GetResponse3", args={
            "chat_history": chat_history,"diagnostic_goal": diagnostic_goal,"expected_fields": expected_fields,"current_question": current_question,
        })
        return baml_py.BamlSyncStream[stream_types.Response3, types.Response3](
          __result__,
          lambda x: typing.cast(stream_types.Response3, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Response3, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GetResponse4(self, chat_history: str,current_question: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Response4, types.Response4]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GetResponse4", args={
            "chat_history": chat_history,"current_question": current_question,
        })
        return baml_py.BamlSyncStream[stream_types.Response4, types.Response4](
          __result__,
          lambda x: typing.cast(stream_types.Response4, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Response4, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluationLayer1(self, chat_history: str,current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluationLayer1", args={
            "chat_history": chat_history,"current_question": current_question,
        }, mode="request")
        return __result__
    def EvaluationLayer2(self, chat_history: str,current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluationLayer2", args={
            "chat_history": chat_history,"current_question": current_question,
        }, mode="request")
        return __result__
    def EvaluationLayer3(self, chat_history: str,diagnostic_goal: str,expected_fields: typing.List[str],current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluationLayer3", args={
            "chat_history": chat_history,"diagnostic_goal": diagnostic_goal,"expected_fields": expected_fields,"current_question": current_question,
        }, mode="request")
        return __result__
    def GetResponse(self, chat_history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetResponse", args={
            "chat_history": chat_history,
        }, mode="request")
        return __result__
    def GetResponse2(self, chat_history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetResponse2", args={
            "chat_history": chat_history,
        }, mode="request")
        return __result__
    def GetResponse3(self, chat_history: str,diagnostic_goal: str,expected_fields: typing.List[str],current_question: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetResponse3", args={
            "chat_history": chat_history,"diagnostic_goal": diagnostic_goal,"expected_fields": expected_fields,"current_question": current_question,
        }, mode="request")
        return __result__
    def GetResponse4(self, chat_history: str,current_question: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetResponse4", args={
            "chat_history": chat_history,"current_question": current_question,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def EvaluationLayer1(self, chat_history: str,current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluationLayer1", args={
            "chat_history": chat_history,"current_question": current_question,
        }, mode="stream")
        return __result__
    def EvaluationLayer2(self, chat_history: str,current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluationLayer2", args={
            "chat_history": chat_history,"current_question": current_question,
        }, mode="stream")
        return __result__
    def EvaluationLayer3(self, chat_history: str,diagnostic_goal: str,expected_fields: typing.List[str],current_question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluationLayer3", args={
            "chat_history": chat_history,"diagnostic_goal": diagnostic_goal,"expected_fields": expected_fields,"current_question": current_question,
        }, mode="stream")
        return __result__
    def GetResponse(self, chat_history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetResponse", args={
            "chat_history": chat_history,
        }, mode="stream")
        return __result__
    def GetResponse2(self, chat_history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetResponse2", args={
            "chat_history": chat_history,
        }, mode="stream")
        return __result__
    def GetResponse3(self, chat_history: str,diagnostic_goal: str,expected_fields: typing.List[str],current_question: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetResponse3", args={
            "chat_history": chat_history,"diagnostic_goal": diagnostic_goal,"expected_fields": expected_fields,"current_question": current_question,
        }, mode="stream")
        return __result__
    def GetResponse4(self, chat_history: str,current_question: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetResponse4", args={
            "chat_history": chat_history,"current_question": current_question,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))