# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py
# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["EvaluationLayerModel1","EvaluationLayerModel2","EvaluationLayerModel3","ExtractedField","ExtractedField1","Response","Response2","Response3","Response4",]
        ), enums=set(
          ["DiagnosticGoalMetStatus","DiagnosticGoalMetStatus1","ON_TOPIC_STATUS","ON_TOPIC_STATUS_1","TURN_DECISION","USER_INTENT",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)

    # #########################################################################
    # Generated enums 6
    # #########################################################################

    @property
    def DiagnosticGoalMetStatus(self) -> "DiagnosticGoalMetStatusViewer":
        return DiagnosticGoalMetStatusViewer(self)

    @property
    def DiagnosticGoalMetStatus1(self) -> "DiagnosticGoalMetStatus1Viewer":
        return DiagnosticGoalMetStatus1Viewer(self)

    @property
    def ON_TOPIC_STATUS(self) -> "ON_TOPIC_STATUSViewer":
        return ON_TOPIC_STATUSViewer(self)

    @property
    def ON_TOPIC_STATUS_1(self) -> "ON_TOPIC_STATUS_1Viewer":
        return ON_TOPIC_STATUS_1Viewer(self)

    @property
    def TURN_DECISION(self) -> "TURN_DECISIONViewer":
        return TURN_DECISIONViewer(self)

    @property
    def USER_INTENT(self) -> "USER_INTENTViewer":
        return USER_INTENTViewer(self)


    # #########################################################################
    # Generated classes 9
    # #########################################################################

    @property
    def EvaluationLayerModel1(self) -> "EvaluationLayerModel1Viewer":
        return EvaluationLayerModel1Viewer(self)

    @property
    def EvaluationLayerModel2(self) -> "EvaluationLayerModel2Viewer":
        return EvaluationLayerModel2Viewer(self)

    @property
    def EvaluationLayerModel3(self) -> "EvaluationLayerModel3Viewer":
        return EvaluationLayerModel3Viewer(self)

    @property
    def ExtractedField(self) -> "ExtractedFieldViewer":
        return ExtractedFieldViewer(self)

    @property
    def ExtractedField1(self) -> "ExtractedField1Viewer":
        return ExtractedField1Viewer(self)

    @property
    def Response(self) -> "ResponseViewer":
        return ResponseViewer(self)

    @property
    def Response2(self) -> "Response2Viewer":
        return Response2Viewer(self)

    @property
    def Response3(self) -> "Response3Viewer":
        return Response3Viewer(self)

    @property
    def Response4(self) -> "Response4Viewer":
        return Response4Viewer(self)



# #########################################################################
# Generated enums 6
# #########################################################################

class DiagnosticGoalMetStatusAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("DiagnosticGoalMetStatus")
        self._values: typing.Set[str] = set([  "YES",  "NO",  ])
        self._vals = DiagnosticGoalMetStatusValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "DiagnosticGoalMetStatusValues":
        return self._vals


class DiagnosticGoalMetStatusViewer(DiagnosticGoalMetStatusAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class DiagnosticGoalMetStatusValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def YES(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("YES"))
    
    @property
    def NO(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NO"))
    
    


class DiagnosticGoalMetStatus1Ast:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("DiagnosticGoalMetStatus1")
        self._values: typing.Set[str] = set([  "YES",  "NO",  ])
        self._vals = DiagnosticGoalMetStatus1Values(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "DiagnosticGoalMetStatus1Values":
        return self._vals


class DiagnosticGoalMetStatus1Viewer(DiagnosticGoalMetStatus1Ast):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class DiagnosticGoalMetStatus1Values:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def YES(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("YES"))
    
    @property
    def NO(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("NO"))
    
    


class ON_TOPIC_STATUSAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ON_TOPIC_STATUS")
        self._values: typing.Set[str] = set([  "ON_TOPIC",  "OFF_TOPIC",  ])
        self._vals = ON_TOPIC_STATUSValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ON_TOPIC_STATUSValues":
        return self._vals


class ON_TOPIC_STATUSViewer(ON_TOPIC_STATUSAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class ON_TOPIC_STATUSValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def ON_TOPIC(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ON_TOPIC"))
    
    @property
    def OFF_TOPIC(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("OFF_TOPIC"))
    
    


class ON_TOPIC_STATUS_1Ast:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ON_TOPIC_STATUS_1")
        self._values: typing.Set[str] = set([  "ON_TOPIC",  "OFF_TOPIC",  ])
        self._vals = ON_TOPIC_STATUS_1Values(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ON_TOPIC_STATUS_1Values":
        return self._vals


class ON_TOPIC_STATUS_1Viewer(ON_TOPIC_STATUS_1Ast):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class ON_TOPIC_STATUS_1Values:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def ON_TOPIC(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ON_TOPIC"))
    
    @property
    def OFF_TOPIC(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("OFF_TOPIC"))
    
    


class TURN_DECISIONAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("TURN_DECISION")
        self._values: typing.Set[str] = set([  "REPEAT_QUESTION",  "PARAPHRASE_QUESTION",  "ANALYSE_RESPONSE",  ])
        self._vals = TURN_DECISIONValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "TURN_DECISIONValues":
        return self._vals


class TURN_DECISIONViewer(TURN_DECISIONAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class TURN_DECISIONValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def REPEAT_QUESTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("REPEAT_QUESTION"))
    
    @property
    def PARAPHRASE_QUESTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PARAPHRASE_QUESTION"))
    
    @property
    def ANALYSE_RESPONSE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ANALYSE_RESPONSE"))
    
    


class USER_INTENTAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("USER_INTENT")
        self._values: typing.Set[str] = set([  "REPEAT_QUESTION",  "REPHRASE_QUESTION",  "PROVIDED_RESPONSE",  ])
        self._vals = USER_INTENTValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "USER_INTENTValues":
        return self._vals


class USER_INTENTViewer(USER_INTENTAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class USER_INTENTValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def REPEAT_QUESTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("REPEAT_QUESTION"))
    
    @property
    def REPHRASE_QUESTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("REPHRASE_QUESTION"))
    
    @property
    def PROVIDED_RESPONSE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PROVIDED_RESPONSE"))
    
    



# #########################################################################
# Generated classes 9
# #########################################################################

class EvaluationLayerModel1Ast:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("EvaluationLayerModel1")
        self._properties: typing.Set[str] = set([  "on_topic_status",  ])
        self._props = EvaluationLayerModel1Properties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EvaluationLayerModel1Properties":
        return self._props


class EvaluationLayerModel1Viewer(EvaluationLayerModel1Ast):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class EvaluationLayerModel1Properties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def on_topic_status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("on_topic_status"))
    
    


class EvaluationLayerModel2Ast:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("EvaluationLayerModel2")
        self._properties: typing.Set[str] = set([  "user_intent",  "rephrased_question",  ])
        self._props = EvaluationLayerModel2Properties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EvaluationLayerModel2Properties":
        return self._props


class EvaluationLayerModel2Viewer(EvaluationLayerModel2Ast):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class EvaluationLayerModel2Properties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def user_intent(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("user_intent"))
    
    @property
    def rephrased_question(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("rephrased_question"))
    
    


class EvaluationLayerModel3Ast:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("EvaluationLayerModel3")
        self._properties: typing.Set[str] = set([  "is_diagnostic_goal_met",  "extracted_fields",  "diagnostic_gap",  "probe_question",  "acknowledgement",  ])
        self._props = EvaluationLayerModel3Properties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EvaluationLayerModel3Properties":
        return self._props


class EvaluationLayerModel3Viewer(EvaluationLayerModel3Ast):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class EvaluationLayerModel3Properties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def is_diagnostic_goal_met(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("is_diagnostic_goal_met"))
    
    @property
    def extracted_fields(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("extracted_fields"))
    
    @property
    def diagnostic_gap(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("diagnostic_gap"))
    
    @property
    def probe_question(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("probe_question"))
    
    @property
    def acknowledgement(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("acknowledgement"))
    
    


class ExtractedFieldAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ExtractedField")
        self._properties: typing.Set[str] = set([  "field_name",  "field_value",  ])
        self._props = ExtractedFieldProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ExtractedFieldProperties":
        return self._props


class ExtractedFieldViewer(ExtractedFieldAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ExtractedFieldProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def field_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("field_name"))
    
    @property
    def field_value(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("field_value"))
    
    


class ExtractedField1Ast:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ExtractedField1")
        self._properties: typing.Set[str] = set([  "field_name",  "field_value",  ])
        self._props = ExtractedField1Properties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ExtractedField1Properties":
        return self._props


class ExtractedField1Viewer(ExtractedField1Ast):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ExtractedField1Properties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def field_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("field_name"))
    
    @property
    def field_value(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("field_value"))
    
    


class ResponseAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Response")
        self._properties: typing.Set[str] = set([  "grammatical_errors_present",  "corrected_transcript",  "explanation_for_student",  ])
        self._props = ResponseProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ResponseProperties":
        return self._props


class ResponseViewer(ResponseAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ResponseProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def grammatical_errors_present(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("grammatical_errors_present"))
    
    @property
    def corrected_transcript(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("corrected_transcript"))
    
    @property
    def explanation_for_student(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("explanation_for_student"))
    
    


class Response2Ast:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Response2")
        self._properties: typing.Set[str] = set([  "acknowledgement",  "is_answer_satisfactory",  "evidence_for_satisfaction",  "probe_question",  ])
        self._props = Response2Properties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "Response2Properties":
        return self._props


class Response2Viewer(Response2Ast):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class Response2Properties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def acknowledgement(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("acknowledgement"))
    
    @property
    def is_answer_satisfactory(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("is_answer_satisfactory"))
    
    @property
    def evidence_for_satisfaction(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("evidence_for_satisfaction"))
    
    @property
    def probe_question(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("probe_question"))
    
    


class Response3Ast:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Response3")
        self._properties: typing.Set[str] = set([  "is_diagnostic_goal_met",  "extracted_fields",  "diagnostic_gap",  "probe_question",  "acknowledgement",  ])
        self._props = Response3Properties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "Response3Properties":
        return self._props


class Response3Viewer(Response3Ast):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class Response3Properties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def is_diagnostic_goal_met(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("is_diagnostic_goal_met"))
    
    @property
    def extracted_fields(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("extracted_fields"))
    
    @property
    def diagnostic_gap(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("diagnostic_gap"))
    
    @property
    def probe_question(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("probe_question"))
    
    @property
    def acknowledgement(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("acknowledgement"))
    
    


class Response4Ast:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Response4")
        self._properties: typing.Set[str] = set([  "on_topic_status",  "turn_decision",  "rephrased_question",  ])
        self._props = Response4Properties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "Response4Properties":
        return self._props


class Response4Viewer(Response4Ast):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class Response4Properties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def on_topic_status(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("on_topic_status"))
    
    @property
    def turn_decision(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("turn_decision"))
    
    @property
    def rephrased_question(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("rephrased_question"))
    
    

