# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.EvaluationLayerModel1": types.EvaluationLayerModel1,
    "stream_types.EvaluationLayerModel1": stream_types.EvaluationLayerModel1,

    "types.EvaluationLayerModel2": types.EvaluationLayerModel2,
    "stream_types.EvaluationLayerModel2": stream_types.EvaluationLayerModel2,

    "types.EvaluationLayerModel3": types.EvaluationLayerModel3,
    "stream_types.EvaluationLayerModel3": stream_types.EvaluationLayerModel3,

    "types.ExtractedField": types.ExtractedField,
    "stream_types.ExtractedField": stream_types.ExtractedField,

    "types.ExtractedField1": types.ExtractedField1,
    "stream_types.ExtractedField1": stream_types.ExtractedField1,

    "types.Response": types.Response,
    "stream_types.Response": stream_types.Response,

    "types.Response2": types.Response2,
    "stream_types.Response2": stream_types.Response2,

    "types.Response3": types.Response3,
    "stream_types.Response3": stream_types.Response3,

    "types.Response4": types.Response4,
    "stream_types.Response4": stream_types.Response4,


    "types.DiagnosticGoalMetStatus": types.DiagnosticGoalMetStatus,

    "types.DiagnosticGoalMetStatus1": types.DiagnosticGoalMetStatus1,

    "types.ON_TOPIC_STATUS": types.ON_TOPIC_STATUS,

    "types.ON_TOPIC_STATUS_1": types.ON_TOPIC_STATUS_1,

    "types.TURN_DECISION": types.TURN_DECISION,

    "types.USER_INTENT": types.USER_INTENT,

}