# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (2)
# #########################################################################

class Response(BaseModel):
    grammatical_errors_present: bool = Field(description='True if there are any grammatical errors in the transcript')
    corrected_transcript: str = Field(description='The corrected transcript of the user\'s speech')
    explanation_for_student: str = Field(description='The explanation for the student in a conversational tone')

class Response2(BaseModel):
    acknowledgement: str = Field(description='Say a small acknowledgement for the users input')
    is_answer_satisfactory: bool = Field(description='Say whether the answer is correct or not')
    evidence_for_satisfaction: str = Field(description='Provide evidence that user answer is satisfactory')
    probe_question: str = Field(description='Provide a question for the user if answer is not satisfactory to probe them further. Only make this field non-empty if the answer is not satisfactory.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
